language: node_js
node_js:
    - "8.9.1"
sudo: false
install:
    - npm install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - npm test -- --travis
addons:
    apt:
        packages:
            - xvfb

