language: node_js

env:
  global:
    - FORCE_COLOR=1

matrix:
  include:
    - os: linux
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux
      node_js: "10"
      
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
    - /tmp/jest-electron-builder-tests

install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xz && mv yarn-* $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn

addons:
  apt:
    packages:
      - xvfb
      - mocha
         
script:
  - yarn test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
